heat_template_version: 2014-10-16

description: Nova on NFS

parameters:
   server:
     type: string
   nova_nfs_export:
     type: string

resources:
   ExtraPreConfig:
     type: OS::Heat::SoftwareConfig
     properties:
       group: script
       config:
         str_replace:
           template: |
             #!/bin/sh
             mkdir -p /var/lib/nova/instances
             chown nova:nova /var/lib/nova/instances
             chmod 775 /var/lib/nova/instances
             setsebool -P virt_use_nfs 1
             echo "_NOVA_NFS_EXPORT_ /var/lib/nova/instances nfs rw 0 2" >> /etc/fstab
             mount -a
           params:
              _NOVA_NFS_EXPORT_: {get_param: nova_nfs_export}

   ExtraPreDeployment:
     type: OS::Heat::SoftwareDeployment
     properties:
       config: {get_resource: ExtraPreConfig}
       server: {get_param: server}
       actions: ['CREATE','UPDATE']

outputs:
   deploy_stdout:
     description: Deployment reference, used to trigger pre-deploy on changes
     value: {get_attr: [ExtraPreDeployment, deploy_stdout]}
