resource_registry:
  #OS::TripleO::BlockStorage::Net::SoftwareConfig: ./nic-config/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: ./nic-config/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: ./nic-config/controller.yaml
  #OS::TripleO::ObjectStorage::Net::SoftwareConfig: ./nic-config/swift-storage.yaml
  #OS::TripleO::CephStorage::Net::SoftwareConfig: ./nic-config/ceph-storage.yaml

  OS::TripleO::Network::Ports::NetVipMap: /usr/share/openstack-tripleo-heat-templates/network/ports/net_vip_map_external.yaml
  OS::TripleO::Network::Ports::ExternalVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::Network::Ports::InternalApiVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::Network::Ports::StorageVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::Network::Ports::StorageMgmtVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml

  #OS::TripleO::ComputeExtraConfigPre: /root/tripleo/predeploy/compute-predeploy-tasks.yaml
  #OS::TripleO::ControllerExtraConfigPre: /root/tripleo/predeploy/controller-predeploy-tasks.yaml
  #OS::TripleO::NodeExtraConfigPost: /root/tripleo/postdeploy/simple.yaml
  OS::TripleO::NodeExtraConfigPost: /root/tripleo/postdeploy/postdeploy-tasks.yaml

parameter_defaults:
  GlanceBackend: file
  ExternalNetworkVip: 192.168.122.101
  InternalApiNetworkVip: 172.16.0.9
  ControlPlaneIP: 192.168.2.25
  StorageNetworkVip: 172.18.0.9
  StorageMgmtNetworkVip: 172.19.0.10
  PublicVirtualFixedIPs: [{'ip_address':'192.168.122.101'}]

  controllerExtraConfig:
    neutron::agents::metadata::auth_url: http://192.168.2.25:35357/v2.0

  ExtraConfig:
    nova::debug: true
    glance::registry::debug: true
    glance::api::debug: true
    neutron::debug: true
    keystone::debug: true
    cinder::debug: true

  InternalApiNetCidr: 172.16.0.0/24
  TenantNetCidr: 172.17.0.0/24
  StorageNetCidr: 172.18.0.0/24
  StorageMgmtNetCidr: 172.19.0.0/24
  ManagementNetCidr: 172.20.0.0/24
  ExternalNetCidr: 192.168.122.0/24
  InternalApiAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
  TenantAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.0.200'}]
  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]
  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
  ManagementAllocationPools: [{'start': '172.20.0.10', 'end': '172.20.0.200'}]
  # Leave room for floating IPs in the External allocation pool
  ExternalAllocationPools: [{'start': '192.168.122.200', 'end': '192.168.122.240'}]
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 192.168.122.1
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.2.1
  # The IP address of the EC2 metadata server. Generally the IP of the Undercloud
  EC2MetadataIp: 192.168.2.1
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["8.8.8.8","8.8.4.4"]
  InternalApiNetworkVlanID: 201
  StorageNetworkVlanID: 202
  StorageMgmtNetworkVlanID: 203
  TenantNetworkVlanID: 204
  ManagementNetworkVlanID: 205
  ExternalNetworkVlanID: 206
  # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
  NeutronExternalNetworkBridge: "br-ex"
  # Customize bonding options if require
  nova_nfs_export: "192.168.122.1:/data/exports/nova"

  glance_nfs_export: '192.168.122.1:/data/exports/glance'

#  BondInterfaceOvsOptions:
#    "bond_mode=balance-tcp"
