resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: ./nic-config/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: ./nic-config/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: ./nic-config/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: ./nic-config/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: ./nic-config/ceph-storage.yaml
  OS::TripleO::NodeExtraConfigPost: /root/tripleo/postdeploy/postdeploy-tasks.yaml

  OS::TripleO::Network::Ports::NetVipMap: /usr/share/openstack-tripleo-heat-templates/network/ports/net_vip_map_external.yaml
  OS::TripleO::Network::Ports::ExternalVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::Network::Ports::InternalApiVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::Network::Ports::StorageVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::Network::Ports::StorageMgmtVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::Network::Ports::RedisVipPort: /usr/share/openstack-tripleo-heat-templates/network/ports/from_service.yaml

parameter_defaults:
  ControllerHostnameFormat: 'ctrl-%index%-orangeinfra'
  ComputeHostnameFormat: 'cmpt-%index%-orangeinfra'

  ExternalNetworkVip: 192.168.123.9
  InternalApiNetworkVip: 172.16.0.9
  ControlPlaneIP: 10.0.0.9
  StorageNetworkVip: 172.18.0.9
  StorageMgmtNetworkVip: 172.19.0.10
  ServiceVips:
    redis: 172.16.0.8
  controllerExtraConfig:
    neutron::agents::metadata::auth_url: http://10.0.0.81:35357/v2.0

  InternalApiNetCidr: 172.16.0.0/24
  TenantNetCidr: 172.17.0.0/24
  StorageNetCidr: 172.18.0.0/24
  StorageMgmtNetCidr: 172.19.0.0/24
  ManagementNetCidr: 172.20.0.0/24
  ExternalNetCidr: 192.168.123.0/24
  InternalApiAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
  TenantAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.0.200'}]
  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]
  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
  ManagementAllocationPools: [{'start': '172.20.0.10', 'end': '172.20.0.200'}]
  # Leave room for floating IPs in the External allocation pool
  ExternalAllocationPools: [{'start': '192.168.123.10', 'end': '192.168.123.100'}]
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 192.168.123.1
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 10.0.0.1
  # The IP address of the EC2 metadata server. Generally the IP of the Undercloud
  EC2MetadataIp: 10.0.0.1
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["8.8.8.8","8.8.4.4"]
  InternalApiNetworkVlanID: 201
  StorageNetworkVlanID: 202
  StorageMgmtNetworkVlanID: 203
  TenantNetworkVlanID: 204
  ManagementNetworkVlanID: 205
  ExternalNetworkVlanID: 206
  # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
  NeutronExternalNetworkBridge: "''"
  # Customize bonding options if required
#  BondInterfaceOvsOptions:
#    "bond_mode=balance-tcp"
#
#parameters:
#  controller_classes:
#    - neutron::policy
#  neutron::policy::policies:
#    reserve_ips:
#      key: 'create_port:fixed_ips'
#      value: 'rule:context_is_advsvc or rule:admin_or_network_owner or rule:regular_user'
#  NeutronEnableIsolatedMetadata: true
