heat_template_version: 2015-04-30


description: >
  multiple post-deployment scripts.

resources:

  SomeExtraConfigScript:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: /root/tripleo/postdeploy/postdeploy-tasks.sh}

  SomeExtraConfig:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: SomeExtraConfigScript}
      actions: ['CREATE', 'UPDATE']
